<?php
/**
 * @file
 * Module used to handle audio object batches through the UI and drush.
 */

/**
 * Implements hook_menu().
 */
function islandora_audio_batch_menu() {
  $items = array();

  $items['islandora/object/%islandora_object/manage/collection/audio_batch'] = array(
    'title' => 'Audio Batch',
    'access callback' => 'islandora_audio_batch_menu_access',
    'access arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_audio_batch_form', 2),
    'file' => 'includes/batch.form.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Menu access callback.
 */
function islandora_audio_batch_menu_access($object) {
  if (!islandora_object_access(ISLANDORA_INGEST, $object)) {
    return FALSE;
  }

  $c = 'COLLECTION_POLICY';
  if (isset($object[$c]) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object[$c])) {
    $cp = new CollectionPolicy($object[$c]->content);

    return array_key_exists('islandora:audioCModel', $cp->getContentModels());
  }

  return FALSE;
}

/**
 * Implements hook_islandora_datastream_ingested().
 *
 * Gives the parent object the TN of its first child.
 */
/*
function islandora_audio_batch_islandora_datastream_ingested(AbstractObject $object, AbstractDatastream $datastream) {
  $create_thumbs = variable_get('islandora_audio_object_thumbnail_child', TRUE);
  if ($create_thumbs) {
    $rels_predicate = variable_get('islandora_audio_object_relationship', 'isConstituentOf');
    $part_of = $object->relationships->get(FEDORA_RELS_EXT_URI, $rels_predicate);
    if (isset($part_of[0]['object']['value'])) {
      $parent_pid = $part_of[0]['object']['value'];
      $escaped_parent_pid = str_replace(':', '_', $parent_pid);
      $sequence_numbers = $object->relationships->get(ISLANDORA_RELS_EXT_URI, "isSequenceNumberOf$escaped_parent_pid");
      if (isset($sequence_numbers[0]['object']['value'])) {
        $sequence_number = $sequence_numbers[0]['object']['value'];
        // Use the TN from the first child (i.e., sequence number 1).
        if ($sequence_number == '1') {
          $parent_object = islandora_object_load($parent_pid);
          if ($datastream->id == 'TN' && !$parent_object['TN']) {
            islandora_audio_object_update_parent_thumbnail($parent_object);
          }
        }
      }
    }
  }
}
*/